2020-10-26 05:06:17,230 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-26 05:06:20,238 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-26 05:06:36,686 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-26 05:06:36,748 - autoReconnect - INFO - 找到登录连接按钮
2020-10-26 05:06:36,811 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-26 05:06:40,961 - autoReconnect - INFO - 点击登录按钮成功
2020-10-26 05:06:41,696 - autoReconnect - INFO - 上线成功
2020-10-26 10:37:26,301 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 10:37:26,567 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 10:37:27,145 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 10:37:27,145 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 10:40:55,261 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 10:40:55,573 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 10:40:56,135 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 10:40:56,135 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 12:58:29,284 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 12:58:29,424 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 12:58:30,032 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 12:58:30,095 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 12:58:58,493 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 12:58:58,852 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 12:58:59,446 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 12:58:59,555 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 13:00:24,355 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 13:00:24,480 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 13:00:25,134 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 13:00:25,259 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 13:01:34,052 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 13:01:34,278 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 13:01:34,892 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 13:01:34,970 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 13:01:40,117 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-10-26 16:50:17,355 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 16:50:17,479 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 16:50:18,072 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 16:50:18,150 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 16:50:23,477 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-10-26 16:50:28,803 - autoReconnect - WARNING - 网络连接不通,累计:1
2020-10-26 16:50:34,313 - autoReconnect - WARNING - 网络连接不通,累计:2
2020-10-26 16:50:34,328 - autoReconnect - WARNING - 网络连接不通>2,正在尝试断线重连
2020-10-26 16:50:34,453 - autoReconnect - INFO - 找到断开连接按钮
2020-10-26 16:50:34,515 - autoReconnect - INFO - 鼠标双击成功,pot176,370
2020-10-26 16:50:35,108 - autoReconnect - INFO - 点击断开按钮成功
2020-10-26 16:51:15,705 - autoReconnect - INFO - 发现自助排障工具窗口, 窗口句柄:263256
2020-10-26 16:51:15,721 - autoReconnect - INFO - 已经向排障工具发送结束进程指令 True
2020-10-26 16:51:16,752 - autoReconnect - INFO - Stop fixTools Success
2020-10-26 16:51:25,786 - autoReconnect - INFO - 客户端遇到错误,即将重试
2020-10-26 16:51:25,942 - autoReconnect - INFO - 找到重试按钮
2020-10-26 16:51:26,004 - autoReconnect - INFO - 鼠标双击成功,pot79,408
2020-10-26 16:51:28,487 - autoReconnect - INFO - 点击重试成功
2020-10-26 16:51:33,012 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-26 16:51:33,074 - autoReconnect - INFO - 找到登录连接按钮
2020-10-26 16:51:33,137 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-26 16:51:39,175 - autoReconnect - INFO - 点击登录按钮成功
2020-10-26 16:51:39,892 - autoReconnect - INFO - 上线成功
2020-10-26 16:52:23,641 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 16:52:23,828 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 16:52:24,437 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 16:52:24,500 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 16:52:29,797 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-10-26 16:52:35,202 - autoReconnect - WARNING - 网络连接不通,累计:1
2020-10-26 16:52:40,609 - autoReconnect - WARNING - 网络连接不通,累计:2
2020-10-26 16:52:40,609 - autoReconnect - WARNING - 网络连接不通>2,正在尝试断线重连
2020-10-26 16:52:40,703 - autoReconnect - INFO - 找到断开连接按钮
2020-10-26 16:52:40,765 - autoReconnect - INFO - 鼠标双击成功,pot176,370
2020-10-26 16:52:41,296 - autoReconnect - INFO - 点击断开按钮成功
2020-10-26 16:52:45,847 - autoReconnect - WARNING - 卡在断开中时间超过60s 将重启客户端
2020-10-26 16:52:46,331 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 212, in main
    if(not cutScreenShotFitPrgm()):
  File "autoReconnect.py", line 564, in cutScreenShotFitPrgm
    if(pot[0]<0 or pot[1]<0):
TypeError: 'NoneType' object is not subscriptable

2020-10-26 16:52:46,346 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 16:52:46,346 - autoReconnect - ERROR - 校园客户端程序没有启动, 正在尝试重启客户端
2020-10-26 16:52:49,484 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 17:43:52,910 - autoReconnect - WARNING - 卡在断开中时间超过60s 将重启客户端
2020-10-26 17:43:53,284 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 212, in main
    if(not cutScreenShotFitPrgm()):
  File "autoReconnect.py", line 564, in cutScreenShotFitPrgm
    if(pot[0]<0 or pot[1]<0):
TypeError: 'NoneType' object is not subscriptable

2020-10-26 17:43:53,284 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 17:43:53,300 - autoReconnect - ERROR - 校园客户端程序没有启动, 正在尝试重启客户端
2020-10-26 17:43:56,435 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 17:44:09,734 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-26 17:44:09,796 - autoReconnect - INFO - 找到登录连接按钮
2020-10-26 17:44:09,858 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-26 17:44:12,324 - autoReconnect - INFO - 点击登录按钮成功
2020-10-26 17:44:13,182 - autoReconnect - INFO - 上线成功
2020-10-26 21:15:51,852 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-26 21:15:54,943 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:15:55,660 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:15:55,660 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:15:55,660 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:15:56,737 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:15:56,737 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:15:56,752 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:15:57,830 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:15:57,830 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:15:57,845 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:15:58,923 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:15:58,923 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:15:58,923 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:00,000 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:00,016 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:00,016 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:01,096 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:01,096 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:01,096 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:02,172 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:02,188 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:02,188 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:03,265 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:03,265 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:03,281 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:04,357 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:04,357 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:04,357 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:05,450 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:05,466 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:05,466 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:06,542 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:06,558 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:06,558 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:07,634 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:07,650 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:07,650 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:08,713 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:08,713 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:08,728 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:09,805 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:09,805 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:09,820 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:10,897 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:10,912 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:10,912 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:11,989 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:11,989 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:12,004 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:13,082 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:13,082 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:13,097 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:14,174 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:14,189 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:14,189 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:15,266 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:15,281 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:15,281 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:16,373 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:16,373 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:16,373 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:17,450 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:21,305 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:21,321 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:22,397 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:22,397 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:22,413 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:23,475 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:23,475 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:16:23,475 - autoReconnect - ERROR - 客户端窗口前置失败,即将尝试将启动程序...
2020-10-26 21:16:24,583 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9818841218948364
2020-10-26 21:16:27,319 - autoReconnect - INFO - 上线成功
2020-10-26 21:18:14,399 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-26 21:18:14,634 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-26 21:18:15,859 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 203, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 751, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 801, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 594, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-26 21:18:15,875 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-26 21:18:15,875 - autoReconnect - INFO - win32gui前置方式错误,正在尝试使用ctypes方式前置窗口
2020-10-26 21:18:16,718 - autoReconnect - INFO - 发现自助排障工具窗口, 窗口句柄:131246
2020-10-26 21:18:16,718 - autoReconnect - INFO - 已经向排障工具发送结束进程指令 True
2020-10-26 21:18:17,737 - autoReconnect - INFO - Stop fixTools Success
2020-10-26 21:18:18,331 - autoReconnect - INFO - 发现提示窗口,窗口句柄:196746
2020-10-26 21:18:18,331 - autoReconnect - INFO - 这个提示窗口来自客户端,正在尝试关闭窗口
2020-10-26 21:18:18,331 - autoReconnect - INFO - Close notic window Success
2020-10-26 21:18:18,894 - autoReconnect - INFO - 客户端遇到错误,即将重试
2020-10-26 21:18:19,018 - autoReconnect - INFO - 找到重试按钮
2020-10-26 21:18:19,081 - autoReconnect - INFO - 鼠标双击成功,pot79,408
