2020-10-06 12:32:13,482 - autoReconnect - INFO - 上线成功
2020-10-06 13:34:52,878 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-06 13:34:53,050 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-06 13:34:53,878 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-06 13:34:53,878 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-06 14:38:05,364 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-06 14:38:05,489 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-06 14:38:06,072 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-06 14:38:06,072 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-06 18:24:59,401 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-06 18:24:59,529 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-06 18:25:00,118 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-06 18:25:00,119 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-06 18:26:55,098 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-06 18:26:55,228 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-06 18:26:55,794 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-06 18:26:55,796 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-06 18:28:30,381 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-06 18:28:30,560 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-06 18:28:31,113 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-06 18:28:31,114 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-06 19:12:46,884 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-06 19:12:47,132 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-06 19:12:47,704 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-06 19:12:47,705 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-06 22:13:53,392 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-06 22:13:56,424 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-06 22:13:59,436 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-06 22:14:02,437 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-06 22:14:05,451 - autoReconnect - INFO - 找不到客户端窗口,正在尝试打开客户端...
2020-10-06 22:14:10,330 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:11,438 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:12,515 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564185142517
2020-10-06 22:14:13,592 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:14,668 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:15,776 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:16,947 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564185142517
2020-10-06 22:14:18,071 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:19,148 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:20,240 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:21,316 - autoReconnect - WARNING - 当前截图不属于客户端,正在将客户端调前... 精度:0.9984564781188965
2020-10-06 22:14:23,813 - autoReconnect - INFO - 上线成功
2020-10-06 22:14:24,671 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-10-06 22:14:26,278 - autoReconnect - WARNING - 网络连接不通,累计:1
2020-10-06 22:14:27,808 - autoReconnect - WARNING - 网络连接不通,累计:2
2020-10-06 22:14:27,839 - autoReconnect - WARNING - 网络连接不通>2,正在尝试断线重连
2020-10-06 22:14:27,948 - autoReconnect - INFO - 找到断开连接按钮
2020-10-06 22:14:28,057 - autoReconnect - INFO - 鼠标双击成功,pot176,370
2020-10-06 22:14:28,791 - autoReconnect - INFO - 点击断开按钮成功
2020-10-06 22:14:28,801 - autoReconnect - INFO - 发现提示窗口,窗口句柄:132390
2020-10-06 22:14:28,811 - autoReconnect - INFO - 这个提示窗口来自客户端,正在尝试关闭窗口
2020-10-06 22:14:28,821 - autoReconnect - INFO - Close notic window Success
2020-10-06 22:14:32,227 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-06 22:14:32,336 - autoReconnect - INFO - 找到登录连接按钮
2020-10-06 22:14:32,399 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-06 22:14:34,849 - autoReconnect - INFO - 点击登录按钮成功
2020-10-06 22:14:35,582 - autoReconnect - INFO - 上线成功
2020-10-07 00:18:19,685 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 00:18:19,807 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 00:18:20,342 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 00:18:20,343 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 02:38:29,656 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 02:38:29,785 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 02:38:30,305 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 02:38:30,306 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 03:46:41,985 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 03:46:42,115 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 03:46:42,635 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 03:46:42,636 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 07:28:43,445 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 07:28:43,582 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 07:28:44,101 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 07:28:44,102 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 10:43:56,523 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 10:43:56,648 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 10:43:57,167 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 10:43:57,169 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 11:02:34,848 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 11:02:34,977 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 11:02:35,497 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 11:02:35,498 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 12:38:52,398 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 12:38:52,515 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 12:38:53,055 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 12:38:53,056 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 12:39:03,505 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 12:39:03,621 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 12:39:04,143 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 12:39:04,143 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 14:23:29,225 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 14:23:29,348 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 14:23:29,866 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 14:23:29,867 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 15:12:07,250 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 15:12:07,378 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 15:12:07,900 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 15:12:07,901 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 16:39:54,930 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 16:39:55,054 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 16:39:55,576 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 16:39:55,577 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 18:37:01,988 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 18:37:02,109 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 18:37:02,632 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 18:37:02,633 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 20:13:24,264 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 20:13:24,533 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 20:13:25,076 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 20:13:25,077 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 20:35:42,027 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 20:35:42,296 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 20:35:42,821 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 20:35:42,822 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 20:50:42,014 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 20:50:42,303 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 20:50:42,833 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 20:50:42,835 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 22:26:34,006 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 22:26:34,288 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 22:26:34,825 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 22:26:34,826 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-07 23:02:06,103 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-07 23:02:06,255 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-07 23:02:06,794 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-07 23:02:06,796 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 04:27:07,531 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 04:27:07,656 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 04:27:08,187 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 04:27:08,187 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 08:16:39,491 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 08:16:39,615 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 08:16:40,132 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 08:16:40,132 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 08:49:55,620 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 08:49:55,745 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 08:49:56,261 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 08:49:56,261 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 11:14:05,418 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 11:14:05,542 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 11:14:06,058 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 11:14:06,058 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 13:08:31,838 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 13:08:31,964 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 13:08:32,510 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 13:08:32,510 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 14:29:57,253 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 14:29:57,390 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 14:29:57,947 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 14:29:57,947 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 15:14:26,676 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 15:14:26,802 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 15:14:27,334 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 15:14:27,335 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 15:56:41,629 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 15:56:41,764 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 15:56:42,300 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 15:56:42,301 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 17:25:11,078 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 17:25:11,198 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 17:25:11,754 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 17:25:11,755 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 19:39:01,385 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 19:39:01,510 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 19:39:02,041 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 19:39:02,041 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 21:13:02,174 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 21:13:02,298 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 21:13:02,829 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 21:13:02,829 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 22:14:34,220 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 22:14:34,345 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 22:14:34,891 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 22:14:34,891 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 22:14:36,110 - autoReconnect - WARNING - 网络连接不通,累计:0
2020-10-08 22:14:37,298 - autoReconnect - WARNING - 网络连接不通,累计:1
2020-10-08 22:14:38,500 - autoReconnect - WARNING - 网络连接不通,累计:2
2020-10-08 22:14:38,516 - autoReconnect - WARNING - 网络连接不通>2,正在尝试断线重连
2020-10-08 22:14:38,594 - autoReconnect - INFO - 找到断开连接按钮
2020-10-08 22:14:38,656 - autoReconnect - INFO - 鼠标双击成功,pot176,370
2020-10-08 22:14:39,125 - autoReconnect - INFO - 点击断开按钮成功
2020-10-08 22:14:48,376 - autoReconnect - INFO - 即将操作客户端即将登陆
2020-10-08 22:14:48,422 - autoReconnect - INFO - 找到登录连接按钮
2020-10-08 22:14:48,485 - autoReconnect - INFO - 鼠标双击成功,pot176,321
2020-10-08 22:14:52,053 - autoReconnect - INFO - 点击登录按钮成功
2020-10-08 22:14:52,614 - autoReconnect - INFO - 上线成功
2020-10-08 22:18:24,967 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 22:18:25,076 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 22:18:25,607 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 22:18:25,607 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 22:29:25,016 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 22:29:25,125 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 22:29:25,641 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 22:29:25,641 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-08 23:07:34,195 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-08 23:07:34,321 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-08 23:07:34,851 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-08 23:07:34,851 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
2020-10-09 00:08:59,600 - autoReconnect - WARNING - 网络异常,已切出lazyMode
2020-10-09 00:08:59,709 - autoReconnect - WARNING - 客户端窗口应该是被隐藏了,窗口位置不正确
2020-10-09 00:09:00,240 - autoReconnect - ERROR - Traceback (most recent call last):
  File "autoReconnect.py", line 192, in main
    iscws,rs_client = isClientWindowShot()
  File "autoReconnect.py", line 722, in isClientWindowShot
    return matchClientWindow()
  File "autoReconnect.py", line 759, in matchClientWindow
    matchResult = find_picture(cv2.imread("screenshot_crop.jpg"),cv2.imread("./template/window_top.jpg"))#判断登录通知
  File "autoReconnect.py", line 565, in find_picture
    result = cv2.matchTemplate(target,template,cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-hfoi92lm\opencv\modules\imgproc\src\templmatch.cpp:1163: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'


2020-10-09 00:09:00,240 - autoReconnect - WARNING - 正在尝试修复找不到窗口的错误
